const {
  SOURCE_PATH = "./source/tasks.csv",
  OUTPUT_PATH = "./output/",
  ERROR_FILE_NAME = "./output/error.txt",
  SUCCESS_FILE_NAME = "./output/success.txt",
  TEAM_VELOCITY = "4",
  MAX_SPRINT_AMOUNT = "50",
  SEPARATOR= ",",
  DIFFICULTY_COLUMN_NAME = "difficulty",
  APP_NAME_COLUMN_NAME = "task",
  PROJECT_START_DAY = "31/01/2019",
  SPRINT_DAYS_DURATION = "14",
  FREE_TIME_PER_SPRINT = 10
} = process.env;

module.exports = {
  SOURCE_PATH,
  OUTPUT_PATH,
  ERROR_FILE_NAME,
  SUCCESS_FILE_NAME,
  TEAM_VELOCITY,
  MAX_SPRINT_AMOUNT,
  SEPARATOR,
  DIFFICULTY_COLUMN_NAME,
  APP_NAME_COLUMN_NAME,
  PROJECT_START_DAY,
  SPRINT_DAYS_DURATION,
  FREE_TIME_PER_SPRINT,
};
